### PR TITLE
add FontSelection object with few methods

### PR DESCRIPTION
**Pull request by jonib3k**
not sure i did everything right...
please check

### CODE REVIEW

**Comment by mattn** [comment]
Good. I don't see any problem in your patch.

**Comment by reujab** [comment]
Since this was merged, I am unable to compile:

```
# github.com/mattn/go-gtk/gtk
could not determine kind of name for C.toGFontSelection
```

**Comment by mattn** [comment]
I can find it in gtk.go.h

**Comment by mattn** [comment]
Sorry, I was wrong. Fixed.

**Pull request merged**
